name: Sync fork with upstream

on:
  schedule:
    - cron: '0 */6 * * *'   # 6時間ごと（UTC）
  workflow_dispatch:         # 手動実行ボタンも出す

# GITHUB_TOKEN の権限をこのワークフローに限定して付与
permissions:
  contents: write

concurrency:
  group: sync-fork
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: ${{ github.event.repository.default_branch }}
      UPSTREAM_REPO: openai/openai-cookbook   # 必要なら自分の upstream に変更
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 履歴が必要（fast-forward 判定やマージ用）
      - name: Set bot identity
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Add upstream & fetch
        run: |
          git remote add upstream https://github.com/${UPSTREAM_REPO}.git || \
          git remote set-url upstream https://github.com/${UPSTREAM_REPO}.git
          git fetch upstream --tags
      - name: Merge upstream into fork default branch
        run: |
          git checkout "$TARGET_BRANCH"
          git merge --ff-only "upstream/$TARGET_BRANCH" || \
          git merge --no-edit "upstream/$TARGET_BRANCH"
      - name: Push back to origin
        run: git push origin "$TARGET_BRANCH"
